const cards = [
    {
        code: "2C",
        value: "2",
        image: "https://deckofcardsapi.com/static/img/2C.png"
    }, {
        code: "3C",
        value: "3",
        image: "https://deckofcardsapi.com/static/img/3C.png"
    }, {
        code: "4C",
        value: "4",
        image: "https://deckofcardsapi.com/static/img/4C.png"
    }, {
        code: "5C",
        value: "5",
        image: "https://deckofcardsapi.com/static/img/5C.png"
    }, {
        code: "6C",
        value: "6",
        image: "https://deckofcardsapi.com/static/img/6C.png"
    }, {
        code: "7C",
        value: "7",
        image: "https://deckofcardsapi.com/static/img/7C.png"
    }, {
        code: "8C",
        value: "8",
        image: "https://deckofcardsapi.com/static/img/8C.png"
    }, {
        code: "9C",
        value: "9",
        image: "https://deckofcardsapi.com/static/img/9C.png"
    }, {
        code: "0C",
        value: "10",
        image: "https://deckofcardsapi.com/static/img/0C.png"
    }, {
        code: "JC",
        value: "JACK",
        image: "https://deckofcardsapi.com/static/img/JC.png"
    }, {
        code: "QC",
        value: "QUEEN",
        image: "https://deckofcardsapi.com/static/img/QC.png"
    }, {
        code: "KC",
        value: "KING",
        image: "https://deckofcardsapi.com/static/img/KC.png"
    }, {
        code: "AC",
        value: "ACE",
        image: "https://deckofcardsapi.com/static/img/AC.png"
    }, {
        code: "2D",
        value: "2",
        image: "https://deckofcardsapi.com/static/img/2D.png"
    }, {
        code: "3D",
        value: "3",
        image: "https://deckofcardsapi.com/static/img/3D.png"
    }, {
        code: "4D",
        value: "4",
        image: "https://deckofcardsapi.com/static/img/4D.png"
    }, {
        code: "5D",
        value: "5",
        image: "https://deckofcardsapi.com/static/img/5D.png"
    }, {
        code: "6D",
        value: "6",
        image: "https://deckofcardsapi.com/static/img/6D.png"
    }, {
        code: "7D",
        value: "7",
        image: "https://deckofcardsapi.com/static/img/7D.png"
    }, {
        code: "8D",
        value: "8",
        image: "https://deckofcardsapi.com/static/img/8D.png"
    }, {
        code: "9D",
        value: "9",
        image: "https://deckofcardsapi.com/static/img/9D.png"
    }, {
        code: "0D",
        value: "10",
        image: "https://deckofcardsapi.com/static/img/0D.png"
    }, {
        code: "JD",
        value: "JACK",
        image: "https://deckofcardsapi.com/static/img/JD.png"
    }, {
        code: "QD",
        value: "QUEEN",
        image: "https://deckofcardsapi.com/static/img/QD.png"
    }, {
        code: "KD",
        value: "KING",
        image: "https://deckofcardsapi.com/static/img/KD.png"
    }, {
        code: "AD",
        value: "ACE",
        image: "https://deckofcardsapi.com/static/img/aceDiamonds.png"
    }, {
        code: "2H",
        value: "2",
        image: "https://deckofcardsapi.com/static/img/2H.png"
    }, {
        code: "3H",
        value: "3",
        image: "https://deckofcardsapi.com/static/img/3H.png"
    }, {
        code: "4H",
        value: "4",
        image: "https://deckofcardsapi.com/static/img/4H.png"
    }, {
        code: "5H",
        value: "5",
        image: "https://deckofcardsapi.com/static/img/5H.png"
    }, {
        code: "6H",
        value: "6",
        image: "https://deckofcardsapi.com/static/img/6H.png"
    }, {
        code: "7H",
        value: "7",
        image: "https://deckofcardsapi.com/static/img/7H.png"
    }, {
        code: "8H",
        value: "8",
        image: "https://deckofcardsapi.com/static/img/8H.png"
    }, {
        code: "9H",
        value: "9",
        image: "https://deckofcardsapi.com/static/img/9H.png"
    }, {
        code: "0H",
        value: "10",
        image: "https://deckofcardsapi.com/static/img/0H.png"
    }, {
        code: "JH",
        value: "JACK",
        image: "https://deckofcardsapi.com/static/img/JH.png"
    }, {
        code: "QH",
        value: "QUEEN",
        image: "https://deckofcardsapi.com/static/img/QH.png"
    }, {
        code: "KH",
        value: "KING",
        image: "https://deckofcardsapi.com/static/img/KH.png"
    }, {
        code: "AH",
        value: "ACE",
        image: "https://deckofcardsapi.com/static/img/AH.png"
    }, {
        code: "2S",
        value: "2",
        image: "https://deckofcardsapi.com/static/img/2S.png"
     }, {
        code: "3S",
        value: "3",
        image: "https://deckofcardsapi.com/static/img/3S.png"
    }, {
        code: "4S",
        value: "4",
        image: "https://deckofcardsapi.com/static/img/4S.png"
    }, {
        code: "5S",
        value: "5",
        image: "https://deckofcardsapi.com/static/img/5S.png"
    } , {
        code: "6S",
        value: "6",
        image: "https://deckofcardsapi.com/static/img/6S.png"
    } , {
        code: "7S",
        value: "7",
        image: "https://deckofcardsapi.com/static/img/7S.png"
    }, {
        code: "8S",
        value: "8",
        image: "https://deckofcardsapi.com/static/img/8S.png"
    }, {
        code: "9S",
        value: "9",
        image: "https://deckofcardsapi.com/static/img/9S.png"
    }, {
        code: "0S",
        value: "10",
        image: "https://deckofcardsapi.com/static/img/0S.png"
    }, {
        code: "JS",
        value: "JACK",
        image: "https://deckofcardsapi.com/static/img/JS.png"
    }, {
        code: "QS",
        value: "QUEEN",
        image: "https://deckofcardsapi.com/static/img/QS.png"
    }, {
        code: "KS",
        value: "KING",
        image: "https://deckofcardsapi.com/static/img/KS.png"
    }, {
        code: "AS",
        value: "ACE",
        image: "https://deckofcardsapi.com/static/img/AS.png"
    }
];
