

let board = d3.select("#board") 
    .append("svg")
    .attr("height", 1000)
    .attr("width", 1000);

let table = board.append("ellipse")
    .attr("cx", 450)
    .attr("cy", 290)
    .attr("rx", 390)
    .attr("ry", 200)
    .attr("fill", "green")
    .style("stroke", "black")
    .style("stroke-width", 30);

let hero1 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 150)
    .attr("y", 30)
    .attr("width", 100)
    .attr("height", 136)
    .style("fill", "white")
    .style("stroke", "black")

let hero2 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 260)
    .attr("y", 30)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")


let villan1 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 550)
    .attr("y", 30)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let villan2 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 660)
    .attr("y", 30)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let flop1 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 172)
    .attr("y", 250)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let flop2 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 282)
    .attr("y", 250)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let flop3 = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 392)
    .attr("y", 250)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let turn = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png")
    .attr("x", 502)
    .attr("y", 250)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")

let river = board.append("svg:image")
    .attr("xlink:href", "https://opengameart.org/sites/default/files/card%20back%20orange.png") 
    .attr("x", 612)
    .attr("y", 250)
    .attr("width", 100)
    .attr("height", 136)
    .attr("fill", "white")
    .style("stroke", "black")


